# <center>Scikit-Image User Guide - Notes </center>

User Guide: http://scikit-image.org/docs/dev/user_guide.html

API Reference, which contains information about all modules and their functions: http://scikit-image.org/docs/stable/api/api.html

## Getting Started

scikit-image is an image processing package in Python that works with nupy arrays.

In [1]:
import skimage

# The data module contains a lot of image data, camera is one of those.
from skimage import data

camera = data.camera()
type(camera)    # Note that the data is a numpy 2D array
camera.shape

coins = data.coins()
print(coins)

[[ 47 123 133 ...  14   3  12]
 [ 93 144 145 ...  12   7   7]
 [126 147 143 ...   2  13   3]
 ...
 [ 81  79  74 ...   6   4   7]
 [ 88  82  74 ...   5   7   8]
 [ 91  79  68 ...   4  10   7]]
